[package]
name = "yahoo_finance_api"
version = "0.2.3"
authors = ["Mark Beinker <mwb@quantlink.de>"]
edition = "2018"
description = "A rust adapter for the yahoo! finance API to fetch histories of market data quotes."
license = "MIT OR Apache-2.0"
repository = "https://github.com/xemwebe/yahoo_finance_api"
readme = "README.md"
keywords = ["finance", "yahoo", "stock", "quote"]
categories = ["api-bindings"]

[dependencies]
reqwest = "0.9"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
